stages:
  teacher_train:
    cmd: python src/teacher_train.py
    deps:
    - src/utils/utils.py
    - src/teacher_train.py
    params:
    - train-teacher
    outs:
    - models/teacher.pt
    plots:
    - metrics/teacher/training_plot.png

  teacher_test:
    cmd: python src/teacher_test.py
    deps:
    - src/teacher_test.py
    - models/teacher.pt
    outs:
    - data/teacher.npy
    metrics:
    - metrics/teacher/metrics.json
    plots:
    - metrics/teacher/confusion_matrix.png

  student_train:
    cmd: python src/student_train.py
    deps:
      - src/utils/utils.py
      - src/student_train.py
      - data/teacher.npy
    outs:
    - models/student.pt
    plots:
    - metrics/student/training_plot.png

  student_test:
    cmd: python src/student_test.py
    deps:
      - src/student_test.py
      - models/student.pt
    metrics:
      - metrics/student/metrics.json
    plots:
      - metrics/student/confusion_matrix.png


