train-teacher:
  lr: 0.00002
  epochs: 3
  batch_size: 10
  weight_decay: 0.01
  subset_size: 6000 # None if you want to use the entire dataset

train-student:
  lr: 0.0001
  epochs: 10
  batch_size: 32
  temperature: 5
  alpha: 0.3
  subset_size: 6000 # None if you want to use the entire dataset
