train-teacher:
  lr: 0.00002
  epochs: 1
  batch_size: 64

train-student:
  lr: 0.00005
  epochs: 2
  batch_size: 64
  temperature: 3
  alpha: 0.8

core:
  subset_size: 100 # None if you want to use the entire dataset