image:
  tag: 2.38.0
  pullPolicy: IfNotPresent

worker:
  groupName: workergroup
  replicas: 2
  minReplicas: 1
  maxReplicas: 4
  image:
    repository: rayproject/ray
    tag: 2.38.0
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: "4"
      memory: "16Gi"
    requests:
      cpu: "2"
      memory: "12Gi"
