name: Ray Serve Deployment

on:
  push:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9.20'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install "ray[data,train,tune,serve]==2.38.0"
          pip install "dvc[gs]"
          pip install -r requirements.txt

      - name: DVC Pull
        run: dvc pull

      - name: Build teacher_app
        run: ray serve build src.ray_serve:teacher_app -o teacher_serve_config.yaml

      - name: Build student_app
        run: ray serve build src.ray_serve:student_app -o student_serve_config.yaml

      - name: Install kubectl
        run: |
          sudo apt-get update
          sudo apt-get install -y ca-certificates curl apt-transport-https lsb-release gnupg
          curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
          echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
          sudo apt-get update
          sudo apt-get install -y kubectl

      - name: Set up kubeconfig
        run: |
          mkdir -p ~/.kube
          echo $K8S_CONFIG | base64 -d > ~/.kube/config
        env:
          K8S_CONFIG: ${{ secrets.K8S_CONFIG }}

      - name: Start port-forward
        run: |
          # Forward the Ray Dashboard to localhost:8265
          kubectl port-forward service/raycluster-kuberay-head-svc 8265:8265 > port-forward.log 2>&1 &
          sleep 5
          if ! nc -z localhost 8265; then
              echo "Port-forward failed to start. Logs:"
              cat port-forward.log
              exit 1
          fi

      - name: Deploy teacher_app
        run: ray serve deploy teacher_serve_config.yaml --address http://localhost:8265

      - name: Deploy student_app
        run: ray serve deploy student_serve_config.yaml --address http://localhost:8265

      - name: Port-forward Ray Serve HTTP Endpoint
        run: |
          kubectl port-forward service/raycluster-kuberay-head-svc 8000:8000 > port-forward-serve.log 2>&1 &
          sleep 5
          if ! nc -z localhost 8000; then
              echo "Port-forward of serve endpoint failed. Logs:"
              cat port-forward-serve.log
              exit 1
          fi

      - name: Test Deployment
        run: |
          python test/test_ray_serve.py

      # Upload the generated configuration artifacts for debugging or archiving
      - name: Upload teacher_serve_config.yaml artifact
        uses: actions/upload-artifact@v2
        with:
          name: teacher_serve_config_artifact
          path: teacher_serve_config.yaml

      - name: Upload student_serve_config.yaml artifact
        uses: actions/upload-artifact@v2
        with:
          name: student_serve_config_artifact
          path: student_serve_config.yaml
